apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image }}
        volumeMounts:
          - name: persistent-storage
            mountPath: /app/staticfiles
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DATABASE_URL
        - name: DJANGO_SUPERUSER_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SUPERUSER_EMAIL
        - name: DJANGO_SUPERUSER_USERNAME
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SUPERUSER_USERNAME
        - name: DJANGO_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SUPERUSER_PASSWORD
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom: 
            configMapKeyRef:
              name: django-configmap
              key: DJANGO_ALLOWED_HOSTS
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: django-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: django-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80