apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image }}
        volumeMounts:
          - name: persistent-storage
            mountPath: /app/staticfiles
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
        env:
        {{- range $key, $value := .Values.secretValues }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: {{ $value }}
        {{- end }}
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.appName }}-configmap
              key: DJANGO_ALLOWED_HOSTS
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80