repositories:
  - name: elastic
    url: https://helm.elastic.co
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: 1.13.1
    createNamespace: true
  - name: djangoapp
    chart: ./djangoapp
    values:
      - ./djangoapp/values.yaml
  - name: elasticsearch
    chart: elastic/elasticsearch
    version: 8.5.1
    values:
      - ./values-elasticsearch.yaml
  - name: kibana
    chart: elastic/kibana
    version: 8.5.1
    values:
      - ./values-kibana.yaml