---
- name: Setup & Generate CA, TLS certs and Kubeconfigs
  hosts: all

  roles:
  - setup
  - ca_tls
  - kubeconfigs

- name: Generating the Data Encryption Config & Bootstrapping Etcd and Control Plane
  hosts: masters

  roles:
  - data_encrypt
  - etcd_bootstrap
  - control_bootstrap

- name: Bootstrapping worker nodes
  hosts: workers
  become: yes

  roles:
  - worker_bootstrap

- name: Setup kubectl locally
  hosts: 127.0.0.1
  connection: local

  roles:
  - kubectl_conf

- name: Setup networking
  hosts: all

  roles:
  - networking

- name: Setup cluster add-ons
  hosts: masters

  roles:
  - dns_addons

- name: Smoke Test
  hosts: 127.0.0.1
  connection: local

  roles:
  - smoke_test