version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: its_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  djangoapp:
    build:
      dockerfile: Dockerfile
    container_name: its_django_app
    environment:
      DJANGO_ALLOWED_HOSTS: '*'
      DATABASE_URL: ${DATABASE_URL}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
