---
- name: Setup Database
  hosts: db01

  roles:
  - db_setup

- name: Setup Application
  hosts: webservers

  roles:
  - app_setup

- name: Deploy Application
  hosts: webservers

  roles:
  - deploy
