apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "djangoapp.fullname" . }}
  labels:
    {{- include "djangoapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "djangoapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "djangoapp.selectorLabels" . | nindent 6 }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image }}
        volumeMounts:
          - name: persistent-storage
            mountPath: /app/staticfiles
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.probes.port }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
        env:
        {{- range $key, $value := .Values.secretValues }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: {{ $value }}
        {{- end }}
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.appName }}-configmap
              key: DJANGO_ALLOWED_HOSTS
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "djangoapp.fullname" . }}
labels:
  {{- include "djangoapp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "djangoapp.selectorLabels" . | nindent 6 }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: 8000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "djangoapp.fullname" . }}
labels:
  {{- include "djangoapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-webhook
labels:
  {{- include "djangoapp.labels" . | nindent 4 }}
data:
  podsecurityconfiguration.yaml: |
    apiVersion: pod-security.admission.config.k8s.io/v1beta1
    kind: PodSecurityConfiguration
    defaults:
      enforce-version: "latest"
      audit-version: "latest"
      warn-version: "latest"