apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "djangoapp.fullname" . }}
labels:
  {{- include "djangoapp.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ppo.devops@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx