apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "djangoapp.fullname" . }}
labels:
  {{- include "djangoapp.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "djangoapp.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.0.0/16
        - podSelector:
            matchLabels:
              {{- include "djangoapp.selectorLabels" . | nindent 6 }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
  - {}

