apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.0.0/16
        - podSelector:
            matchLabels:
              app: {{ .Values.appName }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
  - {}

